name: Build and Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        game: [gta5, rdr2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Adjust decompiler
        run: bun run scripts/adjust_decompiler.js ${{ matrix.game }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Build script decompiler
        run: |
          dotnet build ./vendor/script_decompiler \
            -c Release \
            --output ./bin

      - name: Decompile scripts
        run: bun run scripts/decompile_scripts.js ${{ matrix.game }}

      - name: Create zip archives
        run: |
          cd vendor/${{ matrix.game }}_script_rel/exported
          zip -r ../../../${{ matrix.game }}_script_rel.zip .
          cd -

      - name: Create MP zip archive (RDR2 only)
        if: matrix.game == 'rdr2'
        run: |
          cd vendor/${{ matrix.game }}_script_mp_rel/exported
          zip -r ../../../${{ matrix.game }}_script_mp_rel.zip .
          cd -    

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            script_rel.zip
            script_mp_rel.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
